spring:
  application:
    name: myblog
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            scope:
              - email
              - profile
jwt:
  issuer: guswhd903@naver.com
  secret_key: springboot-study