spring:
  application:
    name: myblog
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true